fix: toString method can now handle 0 as number
sisimomo/Spring-Filter-Query-Builder pull request #15
Opened 2024-08-26 14:26 UTC by mok-liee

hi, i think in some situations it is necessary to have a numeric 0 in the condition.

2024-08-26 14:58 UTC, mok-liee commented
by the way, sorry. i forgot to create a feature branch.

2024-08-29 13:24 UTC, sisimomo requested changes
I see, thanks for the fix. I’ll apply it once the code style is corrected.

2024-08-29 13:24 UTC, sisimomo commented on src/comparators.ts
> +    if (typeof this.value === 'undefined' || this.value === null) return `${this.selector} ${this.comparatorKeyWord}`;
```suggestion
    if (typeof this.value === 'undefined' || this.value === null) {
      return `${this.selector} ${this.comparatorKeyWord}`;
    }
```

2024-08-29 13:57 UTC, mok-liee commented
done :)! big thanks

2024-08-30 18:50 UTC, sisimomo approved these changes

2024-08-30 18:51 UTC, merged